[package]
name = "liquidium_test_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.17.0"
ic-cdk-timers = "0.11.0" # Feel free to remove this dependency if you don't need timers
hex = "0.4.3"
bitcoin = "0.32.3"
serde = { version = "1", features = ["derive"]}
serde_json = "1.0.132"
sha2 = "0.10.8"
ciborium = "0.2.2"
ciborium-io = "0.2.2"
base64 = "0.22.1"
ordinals = "=0.0.12"

[dev-dependencies]
pocket-ic = "5.0.0"